DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS orders CASCADE;


CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(127) NOT NULL,
    description VARCHAR(255),
    price INTEGER NOT NULL,
    stock INTEGER DEFAULT 0
);

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    status VARCHAR(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_item (
    id SERIAL PRIMARY KEY,
    product_id INT NOT NULL,
    order_id INT NOT NULL,
    quantity INTEGER NOT NULL
);
